config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  get 'about_us' => 'pages#about_us'

  get 'why_we_are_better' => 'pages#why_we_are_better'

  get 'pricing' => 'pages#pricing'

  get 'request_a_demo' => 'pages#request_a_demo'

  root 'pages#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about_us
  end

  def why_we_are_better
  end

  def pricing
  end

  def request_a_demo
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
      <div class="container">
        <p class="text-muted">2016 - Apps for Appetites</p>
      </div>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      	<li><%= link_to 'Home', root_path %></li>
        <li><%=link_to 'Why We Are Better', why_we_are_better_path %></li>
        <li><%=link_to 'Pricing', pricing_path %></li>
        <li><%=link_to 'About Us', about_us_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">+1 877 123 1234</a></li>
        <li><%= link_to 'Request a Demo', request_a_demo_path, class: "btn btn-success", style: "color: black;" %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppsForAppetites</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/nav' %>
<div class="container">
	<%= yield %>
</div>
<%= render 'layouts/footer' %>

</body>
</html>

app/views/pages/about_us.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3 text-center">
		<h5>Some details about how we created this amazing product.</h5>
		<h6>MJ Big image goes here with pipelines</h6>
	</div>
</div>

app/views/pages/index.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="text-center">
			<h1>We are dedicated to increasing your restaurants revenue</h1>
		</div>
	</div>
</div>


<div class="row" style="margin-top: 90px;">
	<div class="col-md-6">
		<img src="http://placehold.it/450x150" class="img-responsive">
		<h4>Customized Online Ordering Apps </h4>
		<p>Your restaurant is its own brand. It deserves its own app.</p>
	</div>
	<div class="col-md-6">
		<img src="http://placehold.it/450x150" class="img-responsive">
		<h4>Targeted Marketing</h4>
		<p>We help you farm your delivery area to get your app adopted and used by customers.</p>
	</div>
</div>

<div class="row text-center" style="margin-top: 90px;">
	<h4>Get More Repetitive Orders</h4>
	<iframe width="820" height="515" src="https://www.youtube.com/embed/XQu8TTBmGhA?rel=0&amp;controls=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>
</div>

<div class="row" style="margin-top: 90px;">
	<div class="col-md-6 col-md-offset-3 text-center">
		<div class="well well-lg">
			<h4>We have lots of experience making apps, and we do it really well. That’s a guarantee.</h4>
			<p>Even if you don’t personally use apps yourself, your restaurant deserves to. </p>
			<p>Phone orders are silly. Let us agree on that?</p>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-6">
		<div class="well well-lg">
			<h5>Your restaurant receives orders on a tablet like this.</h5>
			<p>Each order that comes in is… well
			how do I describe this- …is
			Amazing!
			The alternative is not receiving
			orders. Just imagine this empty.
			Click here, we clear it out.</p>
		</div>	
	</div>
	<div class="col-md-6">
		<div class="well well-lg">
			<ul>
				<li>Order 1. Burgers and fries</li>
				<li>Order 2. Burgers and fries</li>
				<li>Order 3. Burgers and fries</li>
				<li>Order 4. Burgers and fries</li>
				<li>Order 5. Burgers and fries</li>
				<li>Order 6. Burgers and fries</li>
				<li>Order 7. Burgers and fries</li>
				<li>Order 8. Burgers and fries</li>
				<li>Order 9. Burgers and fries</li>
				<li>Order 10. Burgers and fries</li>
				<li>Order 11. Burgers and fries</li>
				<li>Order 12. Burgers and fries</li>
				<li>Order 13. Burgers and fries</li>
				<li>Order 14. Burgers and fries</li>
				<li>Order 15. Burgers and fries</li>
			</ul>
		</div>
	</div>
</div>

<div class="row" style="margin-top: 90px;">
	<div class="col-md-6 col-md-offset-3 text-center">
		<h5>We have an incredible team of technologists</h5>
		<h5>as well as marketing professionals</h5>
		<h5>ready to take your restaurant to the next level.</h5>
	</div>
</div>

<div class="row" style="margin-top: 90px;">
	<div class="col-md-6 col-md-offset-3 text-center">
		<a href="#" class="btn btn-primary btn-lg">Request a Demo</a>
		<p>or call</p>
		<p>+1 866 123 1234</p>
	</div>
</div>

app/views/pages/pricing.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3 text-center">
		<h5>Every plan comes with a customized online ordering app for your restaurant and a targeted marketing plan to increase app adoption.</h5>
	</div>
</div>

<div class="row" style="margin-top: 30px;">
	<div class="col-md-6 text-center">
		<h6>Customized App with CMR</h6>
		<p>$199/mo</p>
	</div>
	<div class="col-md-6 text-center">
		<h6>Marketing Services</h6>
		<p>$149/mo</p>
	</div>
</div>

<div class="row" style="margin-top: 90px;">
	<div class="col-md-6 col-md-offset-3 text-center">
		<h5>Our Promises:</h5>
		<p>To make your restaurant better.</p>
		<p>To give your restaurant technology it deserves.</p>
		<p>To make your potential customers adopt this technology</p>
	</div>
</div>

<div class="row" style="margin-top: 90px;">
	<div class="col-md-6 col-md-offset-3 text-center">
		<h5>Questions:</h5>
		<p><strong>Can I cancel at any time?</strong><br>
		Of course. We have a very simple “off-boarding” process.</p>
		<p><strong>Why do I need your marketing services?</strong><br>
		So we get hungry customers in your delivery zone aware that you and your app exist.
		And persuade them to use your app and order from you.</p>
	</div>
</div>

<div class="row" style="margin-top: 90px;">
	<div class="col-md-6 col-md-offset-3 text-center">
		<a href="#" class="btn btn-primary btn-lg">Request a Demo</a>
		<p>or call</p>
		<p>+1 866 123 1234</p>
	</div>
</div>

app/views/pages/request_a_demo.html.erb
<form class="form-horizontal">
  <fieldset>
    <legend class="text-center">Let’s start by talking about your passion, your restaurant and its food!</legend>
    <div class="form-group">
      
      <div class="col-lg-6 col-md-offset-3">
        <input type="text" class="form-control" id="inputEmail" placeholder="Restaurant name">
      </div>
      <div class="col-lg-6 col-md-offset-3">
        <input type="text" class="form-control" id="inputEmail" placeholder="Type of food">
      </div>
      <div class="col-lg-6 col-md-offset-3">
        <input type="text" class="form-control" id="inputEmail" placeholder="Most successful menu item">
      </div>
    </div>

    <legend style="margin-top: 70px;" class="text-center">Let’s talk about your hungry customers, we need to know a little bit more about them so we can build a better app they will use</legend>
    <div class="form-group">
      
      <div class="col-lg-6 col-md-offset-3">
        <input type="text" class="form-control" id="inputEmail" placeholder="Eat in orders per day">
      </div>
      <div class="col-lg-6 col-md-offset-3">
        <input type="text" class="form-control" id="inputEmail" placeholder="Take-out orders per day">
      </div>
      <div class="col-lg-6 col-md-offset-3">
        <input type="text" class="form-control" id="inputEmail" placeholder="Average age">
      </div>
    </div>

    <legend style="margin-top: 70px;" class="text-center">Almost done</legend>
    <div class="form-group">
      
      <div class="col-lg-6 col-md-offset-3">
        <input type="text" class="form-control" id="inputEmail" placeholder="Your first name">
      </div>
      <div class="col-lg-6 col-md-offset-3">
        <input type="text" class="form-control" id="inputEmail" placeholder="Your last name">
      </div>
      <div class="col-lg-6 col-md-offset-3">
        <input type="text" class="form-control" id="inputEmail" placeholder="Your email">
      </div>
      <div class="col-lg-6 col-md-offset-3">
        <input type="text" class="form-control" id="inputEmail" placeholder="Your phone #">
      </div>
      <div class="col-lg-6 col-md-offset-3">
        <input type="text" class="form-control" id="inputEmail" placeholder="Restaurant zip code/ postal code">
      </div>

      <div class="col-lg-12" style="margin-top: 20px;">
        <textarea class="form-control" rows="3" id="textArea"></textarea>
        <span class="help-block">Any info you want to share about your restaurant. Please tell us we love food.</span>
      </div>
    </div>
    <div class="form-group" style="margin-top: 30px;">
      <div class="col-lg-6 col-lg-offset-3">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </fieldset>
</form>

app/views/pages/why_we_are_better.html.erb
<div class="row">
	<h2>Ok you joined a directory style app...</h2>
	<div class="col-md-4">
		<div class="well well-lg">
			<h6>Seems like a good idea until you realize you’re listed next to many, like a lot, ok like a ton of competitors and you don’t get the order volume you expected.</h6>
		</div>
	</div>
	<div class="col-md-4">
		<div class="well well-lg">
			<h6>So you get some orders, but then you have to pay a huge chuck of your margin. Margins are already thin, this really hurts</h6>
		</div>
	</div>
	<div class="col-md-4">
		<div class="well well-lg">
			<h6>You conclude that this style of apps is ineffective for your restaurant.</h6>
		</div>
	</div>
</div>

<div class="row">
	<h2>So then you thought you should make your own app...</h2>
	<div class="col-md-4">
		<div class="well well-lg">
			<h6>Your own apps gets customers thinking about your brand exclusively. In addition, no fees to pay when orders come in. This seems great. Very exciting</h6>
		</div>
	</div>
	<div class="col-md-4">
		<div class="well well-lg">
			<h6>So you get some orders, but then you have to pay a huge chuck of your margin. Margins are already thin, this really hurts</h6>
		</div>
	</div>
	<div class="col-md-4">
		<div class="well well-lg">
			<h6>Finally you have your app. It took longer than you wanted and cost much more than you anticipated. Is there any money left over to market your app? After all your customers have to use it. At least now you know what bugs are. Are those dealt with by the way?</h6>
		</div>
	</div>
</div>

<div class="row">
	<h2>Now imagine you came to Apps for Appetites instead...</h2>
	<div class="col-md-4">
		<div class="well well-lg">
			<h6>We have already build an amazing and robust platform. We can easily customize the app for your restaurant and empower your brand. Plus we make it affordable.</h6>
		</div>
	</div>
	<div class="col-md-4">
		<div class="well well-lg">
			<h6>Within 2 weeks your app is live and running. You are now working directly with your customers accepting orders.</h6>
		</div>
	</div>
	<div class="col-md-4">
		<div class="well well-lg">
			<h6>Next we get you app adopted. Our specialists develop a target marketing strategy that works. This is just as important as the app so we treat it this way. You’re going to enjoy being connected to your customers</h6>
		</div>
	</div>
</div>


<div class="row" style="margin-top: 90px;">
	<div class="col-md-6 col-md-offset-3 text-center">
		<a href="#" class="btn btn-primary btn-lg">Request a Demo</a>
		<p>or call</p>
		<p>+1 866 123 1234</p>
	</div>
</div>